### ISSUE TITLE
Migrate tasks doesn't allow absolute paths

### ISSUE THREAD

**Issue by JoshuaCarter** [symbiote/silverstripe-s3cdn#11]
https://github.com/symbiote/silverstripe-s3cdn/blob/fe988cb244bce1e1b36e55c8549b3cce00e84e0b/code/tasks/SS3MigrateAssetsFromS3.php#L20

https://github.com/symbiote/silverstripe-s3cdn/blob/fe988cb244bce1e1b36e55c8549b3cce00e84e0b/code/tasks/SS4MigrateAssetsFromS3.php#L25

The trim call will strip the leading `/` from an absolute path, e.g. `/var/www/site/` -> `var/www/site`.

**Comment by JoshuaCarter** [comment]
@nglasl if you're cool with changing this then assign to me and I'll PR at some point, but perhaps excluding absolute paths is prefered?

**Comment by nglasl** [comment]
Having it support an absolute path is a good change IMO, as I can see the assets commonly sitting outside the web root for this migration. Might be worth adding a comment to say that it supports both relative and absolute too.

**Comment by nglasl** [comment]
:tada: 

Thanks!

**Comment by JoshuaCarter** [comment]
@nglasl I was thinking this should stay open until I get around to doing the same for the SS4 task :sweat_smile:

**Comment by nglasl** [comment]
@JoshuaCarter if you can, please create a new issue for the SS4 task since it needs more than just the absolute paths added to it.

**Comment by JoshuaCarter** [comment]
Sure.
